# Server Port
server.port=8080

# Profiles
spring.profiles.active=local
# spring.profiles.active=prod

# SpringDoc OpenAPI Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.team.nexus=DEBUG
